/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "AdminWebsite": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
    "GlobalPlatformApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "GlobalPlatformApiAuthorizerPlatformJWTAuthorizorFunction": {
      "name": string
      "type": "sst.aws.Function"
    }
    "GlobalPlatformBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "GlobalPlatformEmail": {
      "configSet": string
      "sender": string
      "type": "sst.aws.Email"
    }
    "GlobalPlatformTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "GoogleClientID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "LambdaAuth": {
      "type": "sst.aws.Auth"
      "url": string
    }
    "UserOrgScoppedAssumeRole": {
      "assumeRoleArn": string
      "type": "sst.sst.Linkable"
    }
  }
}
