/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "MyBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "MyTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "OrganizationsApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
  }
}
